port:  5000
markdown: kramdown
name: "Great Lakes Patriots - Who are my reps?"
url: http://glpaschall2.github.io/GLP-Reps/
encoding: utf-8
timezone: America/Detroit
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyBVoG1VSD0mNwuUoIuQQssxFPBhkTjV87c
